image: python:3.7

stages:
  - test
  - deploy

test:
  variables:
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key: pre-commit
    paths:
      - .cache/pre-commit
  before_script:
    - pip install virtualenv --pre poetry pre-commit
    - virtualenv venv
    - source venv/bin/activate
    - poetry config virtualenvs.create false
    - poetry install --no-root
    - python manage.py migrate
    - python manage.py collectstatic --noinput
  script:
    - pre-commit run -a
    - python manage.py test
  stage: test
  cache:
    paths:
      - .cache/pip

terraform:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: deploy
  needs:
    - test
  script:
    - |
        if [ "${CI_COMMIT_REF_PROTECTED}" != "true" ]; then
            export TF_VAR_cloudflare_token=$cf_readonly_token
        fi
    - cd ${TF_ROOT}
    - gitlab-terraform init
    - gitlab-terraform validate
    - gitlab-terraform fmt
    - gitlab-terraform plan
    - gitlab-terraform plan-json
    - if [ "${CI_COMMIT_REF_PROTECTED}" = "true" ]; then gitlab-terraform apply; fi
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/misc/terraform/
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/production
  cache:
    key: terraform-production
    paths:
      - ${TF_ROOT}/.terraform

deploy to production:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  script:
    - git-push ssh://dokku@projects.stavros.io:16022/pastery
  environment: production
  only:
    - master
