image: python:latest

stages:
  - staticcheck
  - typecheck
  - test
  - deploy

staticcheck:
  before_script:
    - pip install -Ur requirements-dev.txt
  script:
    - flake8 .
  stage: staticcheck

typecheck:
  before_script:
    - pip install -Ur requirements-dev.txt
  script:
    - mypy -s .
  stage: typecheck

test:
  before_script:
    - pip install -Ur requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
  script:
    - python manage.py test
  stage: test

deploy to production:
  stage: deploy
  script: curl https://www.pastery.net/webhook/${PRODUCTION_DEPLOY_KEY}/
  environment: production
  only:
    - master
