image: python:latest

before_script:
  - pip install -Ur requirements.txt
  - python manage.py migrate
  - python manage.py collectstatic --noinput

build:
  script:
    - flake8 .
    - python manage.py test
