repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: "https://github.com/ambv/black"
    rev: 21.12b0
    hooks:
      - id: black
  - repo: "https://github.com/asottile/reorder_python_imports"
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
  - repo: "https://gitlab.com/pycqa/flake8"
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - "--config=setup.cfg"
        language_version: python3
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v0.931
    hooks:
      - id: mypy
        language: system
        name: Run MyPy typing checks.
        entry: 'bash -c "PYTHONPATH=$(pwd):$PYTHONPATH mypy ."'
        pass_filenames: false
        verbose: true
        types:
          - python
  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
        stages:
          - commit
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: bash -c "./manage.py makemigrations --check --dry-run"
        types:
          - python
        pass_filenames: false
        stages:
          - commit
