[tool]
[tool.poetry]
name = "pastery"
description = "The sweetest pastebin in the world."
version = "1.0.0"
authors = []

[tool.poetry.dependencies]
python = ">=3.7"
bleach = "*"
brotlipy = "*"
coverage = "*"
django = "==2.0.*,>=2.0.0"
django-annoying = "*"
django-bootstrap3 = "*"
django-brake = "*"
django-cloudflare-push = "*"
django-debug-toolbar = "==1.*,>=1.4.0"
django-extensions = "~2"
django-ipware = "~=2.1.0"
django-nose = "*"
django-recaptcha = "==1.0.*,>=1.0.4"
django-redis = "*"
django-sendgrid-v5 = "*"
django-tokenauth = "*"
djangoql = "*"
docutils = "==0.*,>=0.12.0"
fake-factory = "==0.5.*,>=0.5.7"
html5lib = "*"
hypothesis = "==3.1.*,>=3.1.0"
markdown = "==2.6.*,>=2.6.5"
mixpanel = "==4.2.*,>=4.2.0"
mixpanel-py-async = "*"
psycopg2-binary = ">=2.7.1"
pygments = "==2.4.2"
pytz = "*"
raven = "*"
requests = "==2.11.*,>=2.11.1"
schema = "==0.4.*,>=0.4.0"
shortuuid = "==0.4.*,>=0.4.2"
sqlparse = "==0.2.*,>=0.2.0"
textile = "==2.2.*,>=2.2.2"
uwsgi = "==2.0.*,>=2.0.11"
werkzeug = "==0.11.*,>=0.11.2"
whitenoise = "*"
django-dotenv = "~1.4.2"
django-webauthin = "~0.0.4"
django-qmethod = "~0.0.3"

[tool.poetry.dev-dependencies]
bpython = "*"
flake8 = "*"
ipython = "*"
django-stubs = "*"
mypy = "*"
