"""
Django settings for pastery project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import random
import re
from subprocess import check_output

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_FROM_EMAIL = "Pastery <noreply@pastery.net>"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "#60=4-b_z(wv06&gdr%zk5+-%r=590zl+x=j4_t1!*a-%&$r&n"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("NODEBUG") is None

ALLOWED_HOSTS = ["*"] if os.environ.get("NODEBUG") is None else [".pastery.net"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    "raven.contrib.django.raven_compat",
    "django_extensions",
    "debug_toolbar",
    "djangoql",
    "tokenauth",
    "bootstrap3",
    "captcha",
    "main",
    "webauthin",
    "api",
]

MIDDLEWARE = [
    "pastery.stats_middleware.StatsMiddleware",
    "django_cloudflare_push.middleware.push_middleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

AUTH_USER_MODEL = "main.User"

SESSION_COOKIE_SECURE = os.environ.get("NODEBUG") is not None
CSRF_COOKIE_SECURE = os.environ.get("NODEBUG") is not None

AUTHENTICATION_BACKENDS = (
    "webauthin.auth_backends.WebAuthinBackend",
    "tokenauth.auth_backends.EmailTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
)

DEFAULT_STYLE = random.choice(
    ["monokai", "solarized", "solarized_dark", "paraiso-dark", "native"]
)

ROOT_URLCONF = "pastery.urls"

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/login/"

WEBAUTHIN_REGISTRATION_ERROR_URL = WEBAUTHIN_REGISTRATION_REDIRECT_URL = "/account/"

IPWARE_META_PRECEDENCE_ORDER = (
    "HTTP_CF_CONNECTING_IP",
    "HTTP_X_FORWARDED_FOR",
    "X_FORWARDED_FOR",
    "HTTP_CLIENT_IP",
    "HTTP_X_REAL_IP",
    "HTTP_X_FORWARDED",
    "HTTP_X_CLUSTER_CLIENT_IP",
    "HTTP_FORWARDED_FOR",
    "HTTP_FORWARDED",
    "HTTP_VIA",
    "REMOTE_ADDR",
)


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pastery.context_processors.current_site",
                "pastery.context_processors.settings",
            ]
        },
    }
]

DEBUG_TOOLBAR_PATCH_SETTINGS = True

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: False
    and (
        (not request.is_ajax())  # type: ignore
        and request.user.is_authenticated
        and request.user.is_superuser
    )
}

WSGI_APPLICATION = "pastery.wsgi.application"

SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

if os.environ.get("IN_DOCKER"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",  # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
            "NAME": "postgres",  # Or path to database file if using sqlite3.
            "USER": "postgres",  # Not used with sqlite3.
            "PASSWORD": "password",  # Not used with sqlite3.
            "HOST": "db",  # Set to empty string for localhost. Not used with sqlite3.
            "PORT": 5432,  # Set to empty string for default. Not used with sqlite3.
        }
    }

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://redis:6379/1",
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }

    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
    SESSION_COOKIE_AGE = 365 * 24 * 60 * 60
elif os.environ.get("DATABASE_URL"):
    # Stuff for when running in Dokku.

    # Parse the DATABASE_URL env var.
    USER, PASSWORD, HOST, PORT, NAME = re.match(  # type: ignore
        r"^postgres://(?P<username>.*?)\:(?P<password>.*?)\@(?P<host>.*?)\:(?P<port>\d+)\/(?P<db>.*?)$",
        os.environ.get("DATABASE_URL", ""),
    ).groups()

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": NAME,
            "USER": USER,
            "PASSWORD": PASSWORD,
            "HOST": HOST,
            "PORT": int(PORT),
        }
    }

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", ""),
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }

    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
    SESSION_COOKIE_AGE = 365 * 24 * 60 * 60

    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, EMAIL_HOST, EMAIL_PORT = re.match(  # type: ignore
        r"^email://(?P<username>.*)\:(?P<password>.*?)\@(?P<host>.*?)\:(?P<port>\d+)\/?$",
        os.getenv("EMAIL_URL", ""),
    ).groups()
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


RATELIMIT_STATUS_CODE = 429
RATELIMIT_CACHE_BACKEND = "pastery.brake_backend.MyBrake"

MIXPANEL_TOKEN = os.getenv("MIXPANEL_TOKEN")

try:
    COMMIT_HASH = check_output(["git", "rev-parse", "--short", "HEAD"])
except:  # noqa
    COMMIT_HASH = b"Not a git repo"

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = "en-us"

LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        }
    },
}

RAVEN_CONFIG = {"dsn": os.getenv("RAVEN_DSN", None)}

CACHING_TIME = 24 * 3600

RECAPTCHA_PUBLIC_KEY = "6LfkpBITAAAAACCMrowwJj4dcUmcjKrZs7CfTqiu"
RECAPTCHA_PRIVATE_KEY = os.getenv("RECAPTCHA_PRIVATE_KEY", "override me")
RECAPTCHA_USE_SSL = True
NOCAPTCHA = True  # Use the new-style NoCAPTCHA.

CLOUDFLARE_EMAIL = os.getenv("CLOUDFLARE_EMAIL", "example@example.com")
CLOUDFLARE_API_KEY = os.getenv("CLOUDFLARE_API_KEY", "example")

ENABLE_CAPTCHA = False

MAX_COMBINED_PASTES = 7

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "_static")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

try:
    from .local_settings import *  # noqa
except ImportError:
    pass
