---
- name: restart nginx
  service: name=nginx state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: update rcd
  shell: initctl reload-configuration

- name: reload uwsgi
  service: name={{ project_name }}_uwsgi state=reloaded

- name: restart uwsgi
  service: name={{ project_name }}_uwsgi state=restarted

- name: migrate
  shell: "{{ env_root }}/bin/python {{ project_root }}/manage.py migrate --noinput"

- name: collectstatic
  shell: "{{ env_root }}/bin/python {{ project_root }}/manage.py collectstatic --noinput"

- name: collectstatic
  shell: "{{ env_root }}/bin/python {{ project_root }}/manage.py compilemessages"
