# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20151206_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
