# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 07:54
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import main.models


class Migration(migrations.Migration):
    dependencies = [("main", "0004_auto_20151206_0811")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                default=main.models.generate_api_key,
                help_text="Your API key.",
                max_length=64,
                verbose_name="API key",
            ),
        )
    ]
