# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0006_auto_20151208_0802")]

    operations = [
        migrations.AddField(
            model_name="paste", name="user_address", field=models.CharField(blank=True, max_length=1000)
        )
    ]
