# Generated by Django 2.0.6 on 2019-03-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0016_auto_20181108_2327")]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
            ],
        )
    ]
