# Generated by Django 2.0.13 on 2025-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_auto_20250728_1036"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shadowbanned",
            field=models.BooleanField(
                default=False,
                help_text="Shadowbanned users can use the site but their pastes won't be saved.",
            ),
        ),
    ]
