# Generated by Django 2.0.13 on 2025-07-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_add_shadowbanned_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='spam_processed',
            field=models.BooleanField(default=False, help_text='Whether this paste has been processed for spam detection.'),
        ),
    ]
