# Generated by Django 2.0.13 on 2026-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_auto_20250731_2209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paste",
            name="raw_language",
            field=models.CharField(
                default="autodetect", max_length=100, verbose_name="Language"
            ),
        ),
    ]
