---
- name: Install necessary system packages.
  apt: pkg={{ item }} state=present
  with_items:
    - python-setuptools

- name: Install Python packages.
  easy_install: name={{ item }}
  with_items:
    - pip

- name: Install ansible.
  pip: name=ansible state=latest

- name: Create ansible dir.
  file: state=directory path=/etc/ansible/ owner={{ project_name }} group={{ project_name }}

- name: Copy ansible config.
  template: src=ansible.cfg.j2 dest=/etc/ansible/ansible.cfg mode=644 owner={{ project_name }} group={{ project_name }}
  notify: restart cptwebhook

- name: Copy ansible hosts.
  template: src=hosts.j2 dest=/etc/ansible/hosts mode=644 owner={{ project_name }} group={{ project_name }}

- name: Copy the Captain Webhook init script.
  template: src=cptwebhook.conf.j2 dest=/etc/init/{{ project_name }}_cptwebhook.conf mode=0755 owner={{ project_name }} group={{ project_name }}
  notify:
      - update rcd
      - restart cptwebhook

- name: Start backend.
  service: name={{ project_name }}_cptwebhook state=started
