---
- name: Install necessary system packages.
  apt: pkg={{ item }} state=latest
  with_items:
    - nginx
    - openssl
    - libssl1.0.0

- name: Copy the site config.
  template: src=app.conf.j2 dest=/etc/nginx/sites-enabled/{{ project_name }} mode=644
  notify: reload nginx

- name: Copy the DH parameters.
  copy: src=dh2k.pem dest=/etc/ssl/dh2k.pem mode=644
  notify: reload nginx

- name: Copy the Let's Encrypt user private key.
  copy: src=certs/user.key dest=/etc/ssl/certs/{{ domain }}_user.key mode=600
  notify: reload nginx

- name: Copy the Let's Encrypt domain private key.
  copy: src=certs/domain.key dest=/etc/ssl/certs/{{ domain }}_domain.key mode=600
  notify: reload nginx

- name: Copy the CSR.
  copy: src=certs/domain.csr dest=/etc/ssl/certs/{{ domain }}.csr mode=644
  notify: reload nginx

- name: Copy acme-tiny.
  copy: src=acme_tiny.py dest=/usr/local/bin/acme_tiny.py mode=755
  notify: reload nginx

- name: Copy acme-tiny.
  template: src=get_cert.sh.j2 dest=/usr/local/bin/get_{{ project_name }}_cert.sh mode=755
  notify: reload nginx

- name: Check if a cert exists.
  stat: path=/etc/ssl/certs/{{ domain }}.crt
  register: stat_result

- name: Get the certificate.
  shell: get_cert.sh
  when: stat_result.stat.exists == False

- name: Start backend.
  service: name=nginx state=started
