---
- name: Install necessary system packages.
  apt: pkg={{ item }} state=latest
  with_items:
    - nginx
    - openssl
    - libssl1.0.0

- name: Install Python packages.
  easy_install: name={{ item }}
  with_items:
    - simp_le

- name: Copy the site config.
  template: src=app.conf.j2 dest=/etc/nginx/sites-enabled/{{ project_name }} mode=644
  notify: reload nginx

- name: Copy the DH parameters.
  copy: src=dh2k.pem dest=/etc/ssl/dh2k.pem mode=644
  notify: reload nginx

- name: Make sure the group exists
  group: name={{ project_name }} system=yes

- name: Make sure the user exists
  user: name={{ project_name }} system=yes group={{ project_name }}

- name: Create project dir.
  file: path={{ project_root }}/certs/ owner={{ project_name }} group={{ project_name }} mode=755 state=directory

- name: Copy the certificate-fetching script.
  template: src=get_cert.sh.j2 dest={{ project_root }}/certs/get_cert.sh mode=755

- name: Change permissions.
  shell: chown -R {{ project_name }}:{{ project_name }} {{ project_root }}

- name: Start backend.
  service: name=nginx state=started
